# Generated by Django 5.2.4 on 2025-07-26 22:36

import myapp.models.catalog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myapp.models.catalog.catalog_image_upload_to)),
                ('pdf_file', models.FileField(upload_to=myapp.models.catalog.catalog_pdf_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
