# Generated by Django 5.2.4 on 2025-08-06 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='collections/')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='formats/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='myapp.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('theme', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='colors/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='myapp.collection')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='myapp.format')),
            ],
        ),
    ]
