# Generated by Django 5.2.4 on 2025-08-08 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_collection_format_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('WITH_FORMATS', 'With Formats (Formats → Themes → Colors)'), ('DIRECT_COLORS', 'Direct Colors (Colors grouped by Formats)')], default='WITH_FORMATS', max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='myapp.format'),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colors/'),
        ),
        migrations.AlterField(
            model_name='format',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='format',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='formats/'),
        ),
        migrations.AlterUniqueTogether(
            name='format',
            unique_together={('collection', 'title')},
        ),
        migrations.CreateModel(
            name='FormatTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format_themes', to='myapp.format')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format_themes', to='myapp.theme')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_themes', to='myapp.collection')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_themes', to='myapp.theme')),
            ],
        ),
        migrations.AddField(
            model_name='format',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='formats', through='myapp.FormatTheme', to='myapp.theme'),
        ),
        migrations.AlterField(
            model_name='color',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colors', to='myapp.theme'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('collection', 'format', 'theme', 'title'), name='uniq_color_per_collection_format_theme_title'),
        ),
        migrations.AlterUniqueTogether(
            name='formattheme',
            unique_together={('format', 'theme')},
        ),
        migrations.AlterUniqueTogether(
            name='collectiontheme',
            unique_together={('collection', 'theme')},
        ),
    ]
